### ISSUE TITLE
(ROS) Dependency Extraction : Building ros2 package with local dependent pkgs

### ISSUE THREAD

**Issue by v-snap** [prefix-dev/pixi-build-backends#399]
Following Up https://github.com/prefix-dev/pixi-build-backends/issues/385

#### What could be the issue , its not clear ?

```toml
[package.build.backend]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "humble"
debug-dir = ".build-debug"


[package.build-dependencies]
ros-humble-plansys2-msgs = { path = "../plansys2_msgs" }



```

### Output ?

```bash
└─$ pixi install
Error:   × failed to solve requirements of environment 'default' for platform 'linux-64'
  ├─▶   × failed to extract metadata for package 'ros-humble-plansys2-pddl-parser'
  │   
  ╰─▶   × AttributeError: 'NoneType' object has no attribute 'removeprefix'
```

**Comment by Stanley5249** [comment]
I'm not sure, but have you tried using `[package.host-dependencies]` instead of `[package.build-dependencies]`?

**Comment by noahjutz** [comment]
This is a regression from v0.2.0..v0.3.0. Projects that depend on multiple interdependent pixi-build-ros packages fail on environment activation. Steps to reproduce:

1. clone this [minimal reproducible example](https://github.com/noahjutz/robostack-build-local-package-issue-minimal)
2. `pixi install`

To see it working on v0.2.0, set the pixi-build-ros version [here](https://github.com/noahjutz/robostack-build-local-package-issue-minimal/blob/1b3d0dbeaa2cc02acaa202e546ce1515fd1b674b/src/my_pkg/pixi.toml#L7) from "*" to "0.2.0".
